#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source the .zshrc.d directory
ZSHRC_DIR="${ZDOTDIR:-$HOME}/.config/zshrc.d"
if [[ -d $ZSHRC_DIR ]]
then
  for rcfile in $ZSHRC_DIR/*(.)
  do
    source $rcfile
  done
fi

# Customize to your needs...

alias vi='vim'
export EDITOR='vim'
export VISUAL='vim'
export BROWSER='qutebrowser'

export GOPATH="$HOME/workspace/go"
export GOROOT=/usr/lib/go

path=(
  "$HOME/bin"
  $path
  "$HOME/.gem/ruby/2.1.0/bin"
  "$HOME/.gem/ruby/2.2.0/bin"
  $GOPATH/bin
)

# Fixes colors in termite
eval $(dircolors ~/.dircolors)
. /etc/profile.d/vte.sh

export CHROME_BIN=chromium

alias codex='mpv --loop inf ~/Videos/codex.mp4'
alias lolslides='feh -F -Z -S mtime --reverse -D 0.2 --cycle-once ~/.lolcommits/**'

# ALT+. to repeat last parameter of the previous command
# Works as !$ would
bindkey '\e.' insert-last-word
