#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias vi='vim'
export EDITOR='vim'
export VISUAL='vim'
export BROWSER='qutebrowser'

export GOPATH="$HOME/workspace/go"
export GOROOT=/usr/lib/go

path=(
  "$HOME/bin"
  $path
  "$HOME/.gem/ruby/2.1.0/bin"
  "$HOME/.gem/ruby/2.2.0/bin"
  $GOPATH/bin
)

eval $(dircolors ~/.dircolors)
. /etc/profile.d/vte.sh

